Pool Based memory allocator "complete" Work continues on room code.
Next Task: Get all KoalaMud objects using pool allocator
Exception: The big single use objects do not need to use the pool allocator and listen sockets don't need to be converted.

BKrev: 3da8a0e0ahwXyWeji3YxZvKSRsvpOQ